spring:
  datasource:
    url: jdbc:mysql://sh-cynosdbmysql-grp-4pzl9pbm.sql.tencentcdb.com:21402/smartcampus?&useSSL=false&serverTimezone=UTC
    username: root
    password: 20001010Wl
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
