spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smartcampus?&useSSL=false&serverTimezone=UTC
    username: root
    password: 20001010
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
